src/grails-app/domain/ReportEditorMain/MediaCenter/Media.groovy
/**
 * Copyright (c) 2009/2010, Very Large Business Applications, University Oldenburg. Specifically:
 * Daniel Süpke <suepke@gmx.de>
 * Andreas Solsbach <solsbach@wi-ol.de>
 * Benjamin Wagner vom Berg <wagnervomberg@wi-ol.de>
 * Prof. Dr. Jorge Marx Gomez <jorge.marx.gomez@uni-oldenburg.de>
 * Christian Wenke <cw81@cw81.de>
 * Desislava Dechkova <desislavamd@yahoo.com>
 * Edzard Fisch <edzard.fisch@googlemail.com>
 * Frank Gerken <frank.gerken@uni-oldenburg.de>
 * Gerrit Meerpohl <gerrit.meerpohl@uni-oldenburg.de>
 * Irene Fröhlich <froehlich.irene@web.de>
 * Kerem-Kazim Sezer <Kerem.Sezer@gmx.de>
 * Olaf Roeder <o.roeder@gmx.net>
 * Oliver Norkus <oliver.norkus@googlemail.com>
 * Rachid Lacheheb <rachid.lacheheb@mail.uni-oldenburg.de>
 * Sebastian van Vliet <sebastian.van.vliet@mail.uni-oldenburg.de>
 * Swetlana Lipnitskaya <swetlana.lipnitskaya@uni-oldenburg.de>
 * 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *     * Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */
 
package ReportEditorMain.MediaCenter
import systemadministration.usermanagement.User
import java.util.ArrayList
import ReportEditorMain.ArticleEditor.Article

/**
 *The class MediaCenter matches the "Mediathek" (media library) from the STORM concept paper.
 *All meta-data about the stored media-files is listed in this class.
 *Local files can be uploaded, supportet formats are common picture formats, mp3, ogg and flv.
 *Uploaded files are not stored in the database, but in the filesystem.
 *All media files have to be present in the media library in order to be used in articles.
 *@author Gerrit Meerpohl, Olaf Roeder
 */

class Media {

    //make this class searchable with the searchable plugin
    static searchable = [only: ['name','description']]

    String name //Titel
    String fileName //original name of the file
    String description //Beschreibung
    String alt //HTML Alt Text
    String url
    String fileType //file extension, e.g. jpg, gif, mp3
    String mediaType //file type, e.g. image, sound, video
    Date date
    //the following attributes are for external sources
    String externalUrl

    //variables for subdirectorys and ownership
    String userDirectory
    //owner
    User owner //the person who uploaded the file
    //allow others to see files?
    boolean isPublicMedia = true

    //special view in list.gsp that allows to assign files similar to a dbms view
    static hasMany = [articles:Article, views:ViewID] //List of articles the media files is used in

    static constraints = {
        //set the order
        name(unique:true, maxSize:200)
        fileName(nullable:false, blank:false, unique:true)
        description(nullable:true, blank:true, maxSize:1500)
        alt(nullable:true, blank:true)
        date(blank:true)
        userDirectory(nullable:false, blank:true)
        fileType(nullable:false, blank:false)
        mediaType(nullable:true, blank:true)
        url(nullable:false, blank:false)
        externalUrl(nullable:true, blank:true)
        owner(nullable:false, blank:false)
        isPublicMedia(nullable:false)
        articles(nullable:true)
        views(nullable:true)
    }
}

src/grails-app/controllers/ReportEditorMain/MediaCenter/MediaController.groovy
/**
 * Copyright (c) 2009/2010, Very Large Business Applications, University Oldenburg. Specifically:
 * Daniel Süpke <suepke@gmx.de>
 * Andreas Solsbach <solsbach@wi-ol.de>
 * Benjamin Wagner vom Berg <wagnervomberg@wi-ol.de>
 * Prof. Dr. Jorge Marx Gomez <jorge.marx.gomez@uni-oldenburg.de>
 * Christian Wenke <cw81@cw81.de>
 * Desislava Dechkova <desislavamd@yahoo.com>
 * Edzard Fisch <edzard.fisch@googlemail.com>
 * Frank Gerken <frank.gerken@uni-oldenburg.de>
 * Gerrit Meerpohl <gerrit.meerpohl@uni-oldenburg.de>
 * Irene Fröhlich <froehlich.irene@web.de>
 * Kerem-Kazim Sezer <Kerem.Sezer@gmx.de>
 * Olaf Roeder <o.roeder@gmx.net>
 * Oliver Norkus <oliver.norkus@googlemail.com>
 * Rachid Lacheheb <rachid.lacheheb@mail.uni-oldenburg.de>
 * Sebastian van Vliet <sebastian.van.vliet@mail.uni-oldenburg.de>
 * Swetlana Lipnitskaya <swetlana.lipnitskaya@uni-oldenburg.de>
 * 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *     * Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */
 

package ReportEditorMain.MediaCenter
import java.util.Date
import imagetools.ImageTool
import systemadministration.usermanagement.User
import ReportEditorMain.ArticleEditor.Article
import ReportEditorMain.ReportEditor.Report
import ReportEditorMain.MediaCenter.ViewID

/**
 * This controller holds all actions used in the <i>Media Library</i>
 * <ul>
 * <li>index: same as list</li>
 * <li>thumb: lists all media files, without special functions</li>
 * <li>list: lists all media files</li>
 * <li>listThumbs: controls wether images or other media files should be listed for the Rich Text Editor's media plugin</li>
 * <li>searchFilter: organizes search results</li>
 * <li>searchAJAX: autocomplete for search</li>
 * <li>create: save a local media to the server</li>
 * <li>save: save a local media to the server</li>
 * <li>download: save an external media to the server</li>
 * <li>show: shows a single media</li>
 * <li>update: edit a media</li>
 * <li>edit: edit a media</li>
 * <li>delete: delete a media</li>
 * <li>actionChecked: deletes a chosen list of media</li>
 * <li>updateArticles: updates the list of referenced articles</li>
 * <li>addToView: adds a media to a view</li>
 * <li>removeFromView: removes a media from a view</li>
 * </ul>
 *@author Olaf Roeder
 **/
class MediaController {

    static allowedMethods = [save: "POST", update: "POST", delete: ["POST", "GET"]]
    def mediaService

    /**
     * Standard index action.
     */
    def index = {
        redirect(action: "list", params: params)
    }

    /**
     * Lists all media files, without special functions.
     */
    def thumb = {
        [mediaInstanceList: Media.list(params)]
    }

    /**
     * Standard list action, but with filter and search functionality added.
     */
    def list = {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        def reportList = Report.list() //reportList is needed for Report Structure View
        def articleList = Article.list() //articleList is needed for Report Structure View
        mediaService.checkAndCreateViewIDs() //ViewIDs are needed in the list.gsp to add media to views
        def viewIDList = ViewID.list()

        if (params.mediaType==null || params.mediaType=='all' || params.mediaType==''){
            [mediaInstanceList: Media.list(params), mediaInstanceTotal: Media.count(), reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList]
        } else if(params.mediaType=='img'){
            def imgList = Media.findAllByMediaType('image')
            def result = Media.createCriteria().list(max: 10, offset:params?.offset) {
                like("mediaType","image")
            }
            [mediaInstanceList: result, mediaInstanceTotal: result.totalCount as Integer, reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList]
        } else if(params.mediaType=='vid'){
            def imgList = Media.findAllByMediaType('video')
            def result = Media.createCriteria().list(max: 10, offset:params?.offset) {
                like("mediaType","video")
            }
            [mediaInstanceList: result, mediaInstanceTotal: result.totalCount as Integer, reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList]
        } else if(params.mediaType=='snd'){
            def imgList = Media.findAllByMediaType('sound')
            def result = Media.createCriteria().list(max: 10, offset:params?.offset) {
                like("mediaType","sound")
            }
            [mediaInstanceList: result, mediaInstanceTotal: result.totalCount as Integer, reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList]
        } else if(params.mediaType=='other'){
            def imgList = Media.findAllByMediaType('other')
            def result = Media.createCriteria().list(max: 10, offset:params?.offset) {
                like("mediaType","other")
            }
            [mediaInstanceList: result, mediaInstanceTotal: result.totalCount as Integer, reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList]
        }
    }

    /**
     * Lists thumbnails of media during the Rich Text Editor media insertion dialogue.
     */
    def listThumbs = {
        if(params.type=='image'){
            def imgList = Media.findAllByMediaType('image')
            render(template: "/media/templates/showMediaThumbs", model: [mediaInstanceList:imgList, mediaInstanceTotal: imgList.count()])
        } else if (params.type=='media'){
            def mediaList = Media.findAllByMediaTypeInList(['sound', 'video', 'other'])
            render(template: "/media/templates/showMediaThumbs", model: [mediaInstanceList:mediaList, mediaInstanceTotal: mediaList.count()])
        }
    }

    /**
     * Action for the Grails Searchable Plugin. Three kinds of searches are performed, first an exact search, if no results are returned a wildcards searched follows, if again no results are returned a like search will be done.
     */
    def searchFilter = {
		def reportList = Report.list() //reportList is needed for Report Structure View
        def articleList = Article.list() //articleList is needed for Report Structure View
        def viewIDList = ViewID.list()
		
        if(!params.mediaSearch.equals("") && !params.mediaSearch==null) params.mediaSearch = params.mediaSearch.trim()
        if(!params.mediaSearch){
            render (view: "list", model:[mediaInstanceList: Media.list(params), mediaInstanceTotal:Media.count(), reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList])
        }
        def tilde=false
        if(params.mediaSearch && !params.mediaSearch.isEmpty()){
            def searchResults = Media.searchEvery(params.mediaSearch, reload:true)

            if(searchResults){
                flash.info = "${message(code: 'mediaSearch.search.results', default: 'Search Results')}"
                def resultsTotal = searchResults
                render(view:"list", model:[mediaInstanceList: searchResults, mediaInstanceTotal:resultsTotal.size(), reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList])
            }

            if(!searchResults){
                searchResults = Media.searchEvery("*"+params.mediaSearch+"*", reload:true)
            }

            if(!searchResults){//2. search as like, means ~string~
                def queryItems = new String(params.mediaSearch)
                queryItems.split(" ").each{
                    searchResults = Media.searchEvery(it+"~0.5", reload:true)
                }
                if(searchResults){
                    tilde=true
                }
                flash.info = "${message(code: 'mediaSearch.search.results', default: 'Search Results')}"
            }

            def resultsTotal = searchResults
            render(view:"list", model:[mediaInstanceList: searchResults, tilde:tilde, mediaInstanceTotal:resultsTotal.size(), reportInstanceList:reportList, viewIDInstanceList:viewIDList, articleInstanceList:articleList])
        }
    }

    /**
     * Action to generate search autocompletion.
     */
    def searchAJAX = {
        def mediaList = Media.findAllByNameLike("${params.query}%")

        //Create XML response
        render(contentType: "text/xml") {
            results() {
                mediaList.each { media ->
                    result(){
                        name(media.name)

src/grails-app/views/media/create.gsp
<%@ page import="ReportEditorMain.MediaCenter.Media" %>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="layout" content="admin" />
  <g:set var="entityName" value="${message(code: 'media.label', default: 'Media')}" />
  <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
  <div class="body">
    <h1><g:message code="default.create.label" args="[entityName]" /></h1>

    <g:if test="${flash.message}">
      <div class="message">${flash.message}</div>
    </g:if>
    <g:if test="${flash.info}">
      <div class="info">${flash.info}</div>
    </g:if>

    <g:hasErrors bean="${mediaInstance}">
      <div class="errors">
        <g:renderErrors bean="${mediaInstance}" as="list" />
      </div>
    </g:hasErrors>

    <p><g:message code="media.upload.file" default="Please choose one: upload a local media file ..." /></p>

  <g:uploadForm action="save" method="post" >
    <div class="mediaTable create mediaUpload">
      <table class="list">
        <tbody>
          <tr class="odd">
            <td valign="top" class="name">
              <label><g:message code="media.step1.label" default="File" /></label>
            </td>
            <td valign="top" class="value">
              <input type="file" id="uploadfile" name="uploadfile" />
            </td>
          </tr>

          <tr>
            <td valign="top" class="name">
              <label><g:message code="media.name.label" default="Name" /></label>
            </td>
            <td valign="top" class="value">
        <input type="text" name="name" value="${mediaInstance?.name}"/>
        </td>
        </tr>

        <tr class="odd">
          <td valign="top" class="name">
            <label><g:message code="media.description.label" default="Description" /></label>
          </td>
          <td valign="top" class="value">
        <input type="text" name="description" value="${mediaInstance?.description}" />
        </td>
        </tr>

        <tr>
          <td valign="top" class="name">
            <label><g:message code="media.alt.label" default="ALT" /></label>
          </td>
          <td valign="top" class="value">
        <input type="text" name="alt" value="${mediaInstance?.alt}" />
        </td>
        </tr>

        </tbody>
      </table>
    </div>

    <div class="buttons">
      <span class="button"><input type="submit" name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" /></span>
    </div>
  </g:uploadForm>


  <p><g:message code="media.get.file" default="... or get a file from an online source." /></p>

<g:uploadForm action="download" method="post" >
  <div class="mediaTable create mediaGet">
    <table  class="list">
      <tbody>
        <tr class="odd">
          <td valign="top" class="name">
            <label><g:message code="media.step1a.label" default="Source" /></label>
          </td>
          <td valign="top" class="value"><g:textField id="externalUrl" name="externalUrl" value="${mediaInstance?.externalUrl}" /></td>
      </tr>

      <tr>
        <td valign="top" class="name">
          <label><g:message code="media.name.label" default="Name" /></label>
        </td>
        <td valign="top" class="value">
      <input type="text" name="name" value="${mediaInstance?.name}"/>
      </td>
      </tr>

      <tr class="odd">
        <td valign="top" class="name">
          <label><g:message code="media.description.label" default="Description" /></label>
        </td>
        <td valign="top" class="value">
      <input type="text" name="description" value="${mediaInstance?.description}" />
      </td>
      </tr>

      <tr>
        <td valign="top" class="name">
          <label><g:message code="media.alt.label" default="ALT" /></label>
        </td>
        <td valign="top" class="value">
      <g:textField name="alt" value="${mediaInstance?.alt}" />
      </td>
      </tr>

      </tbody>
    </table>
  </div>
  <div class="buttons">
    <span class="button"><input type="submit" name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" /></span>
  </div>
</g:uploadForm>


</div><%--class="body"--%>
</body>
</html>

src/grails-app/views/media/edit.gsp
<%@ page import="ReportEditorMain.MediaCenter.Media" %>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="layout" content="admin" />
  <g:set var="entityName" value="${message(code: 'media.label', default: 'Media')}" />
  <title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
  <div class="body">
    <h1><g:message code="default.edit.label" args="[entityName]" /></h1>

    <g:if test="${flash.message}">
      <div class="message">${flash.message}</div>
    </g:if>
    <g:if test="${flash.info}">
      <div class="info">${flash.info}</div>
    </g:if>

    <g:hasErrors bean="${mediaInstance}">
      <div class="errors">
        <g:renderErrors bean="${mediaInstance}" as="list" />
      </div>
    </g:hasErrors>

    <g:form method="post" >
      <g:hiddenField name="id" value="${mediaInstance?.id}" />
      <g:hiddenField name="version" value="${mediaInstance?.version}" />

      <div class="mediaTable editMedia mediaUpload">
        <table class="list">
          <tbody>

            <tr>
              <td valign="top" class="name">
                <label><g:message code="media.url.label" default="File" /></label>
              </td>
              <td valign="top" class="value">${fieldValue(bean: mediaInstance, field: 'url')}</td>
            </tr>

            <tr class="odd">
              <td valign="top" class="name">
                <label><g:message code="media.name.label" default="Name" /></label>
              </td>
              <td valign="top" class="value"><g:textField name="name" value="${mediaInstance?.name}" /></td>
          </tr>

          <tr>
            <td valign="top" class="name">
              <label><g:message code="media.description.label" default="Description" /></label>
            </td>
            <td valign="top" class="value"><g:textField name="description" value="${mediaInstance?.description}" /></td>
          </tr>

          <tr class="odd">
            <td valign="top" class="name">
              <label><g:message code="media.alt.label" default="ALT" /></label>
            </td>
            <td valign="top" class="value"><g:textField name="alt" value="${mediaInstance?.alt}" /></td>
          </tr>

          <tr>
            <td valign="top" class="name">
              <label><g:message code="media.date.label" default="Date" /></label>
            </td>
            <td valign="top" class="value">
          <g:datePicker name="date" precision="day" value="${mediaInstance?.date}"  />
          </td>
          </tr>

          <tr class="odd">
            <td valign="top" class="name">
              <label><g:message code="media.fileType.label" default="File Type" /></label>
            </td>
            <td valign="top" class="value">${fieldValue(bean: mediaInstance, field: 'fileType')}</td>
          </tr>

          <tr >
            <td valign="top" class="name">
              <label><g:message code="media.mediaType.label" default="File Type" /></label>
            </td>
            <td valign="top" class="value"><g:select name="mediaType" from="${['image', 'sound', 'video', 'other']}" valueMessagePrefix="media.type" value="${mediaInstance?.mediaType}" /></td>
          </tr>

          <tr class="odd">
            <td valign="top" class="name">
              <label><g:message code="media.owner.label" default="Owner" /></label>
            </td>
            <td valign="top" class="value">${fieldValue(bean: mediaInstance, field: 'owner.username')}</td>
          </tr>

          <tr >
            <td valign="top" class="name">
              <label><g:message code="media.isPublic.label" default="public" /></label>
            </td>
            <td valign="top" class="value"><g:checkBox name="isPublicMedia" value="${mediaInstance?.isPublicMedia}" /></td>
          </tr>

          </tbody>
        </table>
      </div>

      <div class="mediaTable editMedia mediaGet">
        <table>
          <tbody>
            <tr>
              <td valign="top" class="mediaEven leftEdge leftTable">
                <label><g:message code="media.externalUrl.label" default="External Url" /></label>
              </td>
              <td valign="top" class="rightTable">
          <g:textField name="externalUrl" value="${mediaInstance?.externalUrl}" />
          </td>
          </tr>

          </tbody>
        </table>
      </div>

      <g:displayFile media="${mediaInstance}" />

      <div class="buttons">
        <span class="button"><g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" /></span>
        <span class="button"><g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" /></span>
      </div>
    </g:form>
  </div>
</body>
</html>

src/grails-app/views/media/thumb.gsp
<%@ page import="ReportEditorMain.MediaCenter.Media" %>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="${resource(dir:'css/default',file:'main.css')}" />
  <g:set var="entityName" value="${message(code: 'media.label', default: 'Media')}" />
  <title><g:message code="default.list.label" args="[entityName]" /></title>
  <script type="text/javascript" src="${resource(dir:'js/tinymce/jscripts/tiny_mce', file:'tiny_mce_popup.js')}"></script>
  <script language="javascript" type="text/javascript">
  var FileBrowserDialogue = {
  init : function () {
  // Here goes your code for setting your custom things onLoad.
  },
  mySubmit : function (media) {
  //var URL = document.my_form.my_field.value;
  var URL = media;
  var win = tinyMCEPopup.getWindowArg("window");

  // insert information now
  win.document.getElementById(tinyMCEPopup.getWindowArg("input")).value = URL;

  // are we an image browser
  if (typeof(win.ImageDialog) != "undefined")
  {
  // we are, so update image dimensions and preview if necessary
  if (win.ImageDialog.getImageData) win.ImageDialog.getImageData();
  if (win.ImageDialog.showPreviewImage) win.ImageDialog.showPreviewImage(URL);
  }

  // close popup window
  tinyMCEPopup.close();
  }
  }

  tinyMCEPopup.onInit.add(FileBrowserDialogue.init, FileBrowserDialogue);

  </script>

</head>
<body style="background:#e8e8e8;">

<div class="mediaThumbnails">
  <g:include controller="media" action="listThumbs" />
</div>

</body>
</html>